[build]
  base = "Frontend"
  publish = "Frontend/build"
  command = "npm install && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://soulsync-backend.onrender.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://soulsync-backend.onrender.com"