services:
  - type: web
    name: soulsync-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://soulsync:SoulSync2024@soulsynccluster.mongodb.net/soulsync?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: SoulSync2024$ecur3JWT$K3y!@#RandomSecretForProduction
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: sammmradhi@gmail.com
      - key: EMAIL_PASS
        value: fqozuacmijnzapco
      - key: EMAIL_SECURE
        value: false
      - key: ENCRYPTION_KEY
        value: SoulSync2024EncryptionKey123456
      - key: CLIENT_URL
        value: https://soulsync-app.netlify.app